# FRRouting config — dcY-pod3-evpn-rt-1
# PoD3, rack1 EVPN Route Reflector

hostname dcy-pod3-evpn-rt-1
!
route-map ACCEPT-ALL permit 10
exit
!
ip route 0.0.0.0/0 10.13.0.0
!
!
router bgp 65503
 bgp router-id 10.13.0.1
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 neighbor CROSS-POD peer-group
 neighbor CROSS-POD description Cross-PoD EVPN peering
 neighbor CROSS-POD bfd
 neighbor CROSS-POD ebgp-multihop 10
 neighbor CROSS-POD update-source lo
 neighbor PVE-CLIENTS peer-group
 neighbor PVE-CLIENTS remote-as 65503
 neighbor PVE-CLIENTS description Proxmox PVE clients (iBGP EVPN RR)
 neighbor PVE-CLIENTS bfd
 neighbor 10.11.0.1 remote-as 65501
 neighbor 10.11.0.1 peer-group CROSS-POD
 neighbor 10.11.0.1 description dcX-pod1-evpn-rt-1
 neighbor 10.11.0.5 remote-as 65501
 neighbor 10.11.0.5 peer-group CROSS-POD
 neighbor 10.11.0.5 description dcX-pod1-evpn-rt-2
 neighbor 10.12.0.1 remote-as 65502
 neighbor 10.12.0.1 peer-group CROSS-POD
 neighbor 10.12.0.1 description dcX-pod2-evpn-rt-1
 neighbor 10.12.0.5 remote-as 65502
 neighbor 10.12.0.5 peer-group CROSS-POD
 neighbor 10.12.0.5 description dcX-pod2-evpn-rt-2
 neighbor 10.13.0.3 peer-group PVE-CLIENTS
 neighbor 10.13.0.3 description dcY-pod3-pve-1
 neighbor 10.13.0.7 peer-group PVE-CLIENTS
 neighbor 10.13.0.7 description dcY-pod3-pve-2
 !
 address-family l2vpn evpn
  neighbor CROSS-POD activate
  neighbor PVE-CLIENTS activate
  neighbor PVE-CLIENTS route-reflector-client
 exit-address-family
exit
!
end
